services:
  carakube-cluster:
    build:
      context: ./kubernetes
    privileged: true
    networks:
      - carakube-net

  carakube-operator:
    build:
      context: ./operator
    depends_on:
      - carakube-cluster
    networks:
      - carakube-net

  carakube-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - carakube-net

networks:
  carakube-net:
    driver: bridge
