entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

api:
  dashboard: false

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

global:
  sendAnonymousUsage: true

# Define how Traefik talks to other services.
providers:
  docker:
    exposedByDefault: false # Only expose containers with a specific label.
    watch: true
    network: traefik-proxy

# Define the certificate resolver for Let's Encrypt.
certificatesResolvers:
  letsencrypt:
    acme:
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web
